[2020-05-28T13:08:43.968815+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\xampp\htdocs\PFNT\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:182)"} []
[2020-05-28T13:08:53.707066+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\xampp\htdocs\PFNT\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:182)"} []
[2020-05-28T13:15:57.925587+02:00] php.DEBUG: Warning: include(C:\xampp\htdocs\PFNT\var\cache\de_/App_KernelDevDebugContainer.php): failed to open stream: No such file or directory {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\Kernel.php","line":458,"trace":[{"file":"C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\Kernel.php","line":458,"function":"include"}],"count":1}}} []
[2020-05-28T13:15:57.936800+02:00] php.DEBUG: Warning: include(): Failed opening 'C:\xampp\htdocs\PFNT\var\cache\de_/App_KernelDevDebugContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2020-05-28T13:17:02.395210+02:00] php.DEBUG: Warning: include(C:\xampp\htdocs\PFNT\var\cache\de_/App_KernelDevDebugContainer.php): failed to open stream: No such file or directory {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\Kernel.php","line":458,"trace":[{"file":"C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\Kernel.php","line":458,"function":"include"}],"count":1}}} []
[2020-05-28T13:17:02.400178+02:00] php.DEBUG: Warning: include(): Failed opening 'C:\xampp\htdocs\PFNT\var\cache\de_/App_KernelDevDebugContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2020-05-28T13:18:23.282869+02:00] php.DEBUG: Warning: include(C:\xampp\htdocs\PFNT\var\cache\de_/App_KernelDevDebugContainer.php): failed to open stream: No such file or directory {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\Kernel.php","line":458,"trace":[{"file":"C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\Kernel.php","line":458,"function":"include"}],"count":1}}} []
[2020-05-28T13:18:23.288433+02:00] php.DEBUG: Warning: include(): Failed opening 'C:\xampp\htdocs\PFNT\var\cache\de_/App_KernelDevDebugContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2020-05-28T13:19:25.862986+02:00] php.DEBUG: Warning: include(C:\xampp\htdocs\PFNT\var\cache\de_/App_KernelDevDebugContainer.php): failed to open stream: No such file or directory {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\Kernel.php","line":458,"trace":[{"file":"C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\Kernel.php","line":458,"function":"include"}],"count":1}}} []
[2020-05-28T13:19:25.868260+02:00] php.DEBUG: Warning: include(): Failed opening 'C:\xampp\htdocs\PFNT\var\cache\de_/App_KernelDevDebugContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2020-05-28T13:22:25.246872+02:00] php.DEBUG: Warning: include(C:\xampp\htdocs\PFNT\var\cache\de_/App_KernelDevDebugContainer.php): failed to open stream: No such file or directory {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\Kernel.php","line":458,"trace":[{"file":"C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\Kernel.php","line":458,"function":"include"}],"count":1}}} []
[2020-05-28T13:22:25.252097+02:00] php.DEBUG: Warning: include(): Failed opening 'C:\xampp\htdocs\PFNT\var\cache\de_/App_KernelDevDebugContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2020-05-28T16:38:31.100999+02:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2020-05-28T16:38:31.155355+02:00] doctrine.DEBUG: CREATE TABLE migration_versions (version VARCHAR(14) NOT NULL, executed_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', PRIMARY KEY(version)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2020-05-28T16:38:31.193262+02:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2020-05-28T16:38:31.194874+02:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'PFNT' AND TABLE_NAME = 'migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2020-05-28T16:38:31.204177+02:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'migration_versions' */ WHERE k.table_name = 'migration_versions' AND k.table_schema = 'PFNT' /*!50116 AND c.constraint_schema = 'PFNT' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2020-05-28T16:38:31.210483+02:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'migration_versions' AND TABLE_SCHEMA = 'PFNT' ORDER BY SEQ_IN_INDEX ASC [] []
[2020-05-28T16:38:31.214478+02:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'migration_versions' [] []
[2020-05-28T16:39:05.697056+02:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2020-05-28T16:39:05.704168+02:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'PFNT' AND TABLE_NAME = 'migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2020-05-28T16:39:05.746787+02:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'migration_versions' */ WHERE k.table_name = 'migration_versions' AND k.table_schema = 'PFNT' /*!50116 AND c.constraint_schema = 'PFNT' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2020-05-28T16:39:05.747954+02:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'migration_versions' AND TABLE_SCHEMA = 'PFNT' ORDER BY SEQ_IN_INDEX ASC [] []
[2020-05-28T16:39:05.758526+02:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'migration_versions' [] []
[2020-05-28T16:39:05.770825+02:00] doctrine.DEBUG: SELECT version FROM migration_versions [] []
[2020-05-28T16:39:09.394049+02:00] doctrine.DEBUG: SELECT version FROM migration_versions WHERE version IN ('20200528143831') ORDER BY version DESC LIMIT 1 [] []
[2020-05-28T16:39:09.397235+02:00] doctrine.DEBUG: SELECT version FROM migration_versions [] []
[2020-05-28T16:39:09.410246+02:00] doctrine.DEBUG: "START TRANSACTION" [] []
[2020-05-28T16:39:09.557261+02:00] doctrine.DEBUG: CREATE TABLE empleado (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(50) NOT NULL, apellido VARCHAR(50) NOT NULL, fecha_de_nacimiento DATE NOT NULL, rol VARCHAR(30) NOT NULL, usuario_ingreso VARCHAR(20) NOT NULL, contrasena_ingreso VARCHAR(20) NOT NULL, identificador_jefe INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2020-05-28T16:39:09.578286+02:00] doctrine.DEBUG: CREATE TABLE orden (id INT AUTO_INCREMENT NOT NULL, id_empleado INT NOT NULL, id_producto INT NOT NULL, puntos INT NOT NULL, cantidad SMALLINT NOT NULL, estado VARCHAR(10) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2020-05-28T16:39:09.601484+02:00] doctrine.DEBUG: CREATE TABLE periodo (id INT AUTO_INCREMENT NOT NULL, descripcion VARCHAR(50) NOT NULL, monto_base INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2020-05-28T16:39:09.621795+02:00] doctrine.DEBUG: CREATE TABLE periodos (id INT AUTO_INCREMENT NOT NULL, descripcion LONGTEXT NOT NULL, monto_base INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2020-05-28T16:39:09.641332+02:00] doctrine.DEBUG: CREATE TABLE producto (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(50) NOT NULL, descripcion LONGTEXT NOT NULL, imagen_url LONGTEXT NOT NULL, puntos_redimir INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2020-05-28T16:39:09.661745+02:00] doctrine.DEBUG: CREATE TABLE venta (id INT AUTO_INCREMENT NOT NULL, id_vendedor INT NOT NULL, id_periodo VARCHAR(50) NOT NULL, valor_venta INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2020-05-28T16:39:09.680067+02:00] doctrine.DEBUG: INSERT INTO migration_versions (version, executed_at) VALUES (?, ?) ["20200528143831","2020-05-28 14:39:09"] []
[2020-05-28T16:39:09.690519+02:00] doctrine.DEBUG: "COMMIT" [] []
[2020-05-28T17:57:53.024859+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\xampp\htdocs\PFNT\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:182)"} []
[2020-05-28T17:57:53.826186+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"85b79b"},"request_uri":"http://symfony.local/_wdt/85b79b","method":"GET"} []
[2020-05-28T18:03:08.805835+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\xampp\htdocs\PFNT\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:182)"} []
[2020-05-28T18:03:09.170910+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"5ee2c3"},"request_uri":"http://symfony.local/_wdt/5ee2c3","method":"GET"} []
[2020-05-28T18:03:27.546061+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\xampp\htdocs\PFNT\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:182)"} []
[2020-05-28T18:03:28.018600+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"2c6371"},"request_uri":"http://symfony.local/_wdt/2c6371","method":"GET"} []
[2020-05-28T18:03:53.829062+02:00] request.INFO: Matched route "empleado_index". {"route":"empleado_index","route_parameters":{"_route":"empleado_index","_controller":"App\\Controller\\EmpleadoController::index"},"request_uri":"http://symfony.local/empleado/","method":"GET"} []
[2020-05-28T18:03:54.115269+02:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.nombre AS nombre_2, t0.apellido AS apellido_3, t0.fecha_de_nacimiento AS fecha_de_nacimiento_4, t0.rol AS rol_5, t0.usuario_ingreso AS usuario_ingreso_6, t0.contrasena_ingreso AS contrasena_ingreso_7, t0.identificador_jefe AS identificador_jefe_8 FROM empleado t0 [] []
[2020-05-28T18:03:54.419155+02:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-05-28T18:03:54.706356+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b2f33b"},"request_uri":"http://symfony.local/_wdt/b2f33b","method":"GET"} []
[2020-05-28T18:03:57.707762+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\xampp\htdocs\PFNT\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:182)"} []
[2020-05-28T18:03:58.201867+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"1f5ba2"},"request_uri":"http://symfony.local/_wdt/1f5ba2","method":"GET"} []
[2020-05-28T18:04:17.601859+02:00] request.INFO: Matched route "empleado_index". {"route":"empleado_index","route_parameters":{"_route":"empleado_index","_controller":"App\\Controller\\EmpleadoController::index"},"request_uri":"http://symfony.local/empleado/","method":"GET"} []
[2020-05-28T18:04:17.739083+02:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.nombre AS nombre_2, t0.apellido AS apellido_3, t0.fecha_de_nacimiento AS fecha_de_nacimiento_4, t0.rol AS rol_5, t0.usuario_ingreso AS usuario_ingreso_6, t0.contrasena_ingreso AS contrasena_ingreso_7, t0.identificador_jefe AS identificador_jefe_8 FROM empleado t0 [] []
[2020-05-28T18:04:17.809058+02:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-05-28T18:04:18.212576+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"919f81"},"request_uri":"http://symfony.local/_wdt/919f81","method":"GET"} []
[2020-05-28T18:05:09.133214+02:00] request.INFO: Matched route "empleado_new". {"route":"empleado_new","route_parameters":{"_route":"empleado_new","_controller":"App\\Controller\\EmpleadoController::new"},"request_uri":"http://symfony.local/empleado/new","method":"GET"} []
[2020-05-28T18:05:10.343289+02:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-05-28T18:05:10.723286+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"3ac8a0"},"request_uri":"http://symfony.local/_wdt/3ac8a0","method":"GET"} []
[2020-05-28T18:05:16.568880+02:00] request.INFO: Matched route "empleado_index". {"route":"empleado_index","route_parameters":{"_route":"empleado_index","_controller":"App\\Controller\\EmpleadoController::index"},"request_uri":"http://symfony.local/empleado/","method":"GET"} []
[2020-05-28T18:05:16.741915+02:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.nombre AS nombre_2, t0.apellido AS apellido_3, t0.fecha_de_nacimiento AS fecha_de_nacimiento_4, t0.rol AS rol_5, t0.usuario_ingreso AS usuario_ingreso_6, t0.contrasena_ingreso AS contrasena_ingreso_7, t0.identificador_jefe AS identificador_jefe_8 FROM empleado t0 [] []
[2020-05-28T18:05:16.853405+02:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-05-28T18:05:17.180993+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"832354"},"request_uri":"http://symfony.local/_wdt/832354","method":"GET"} []
[2020-05-28T18:13:54.421714+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\xampp\htdocs\PFNT\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\xampp\\htdocs\\PFNT\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:182)"} []
[2020-05-28T18:13:54.970894+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"84a38d"},"request_uri":"http://symfony.local/_wdt/84a38d","method":"GET"} []
